account_id = "ebbd354a5e5728e183b95c92fbcfb770"
name = "cf-worker-status-page-pro"
main = "./src/worker/index.ts"
compatibility_flags = ["streams_enable_constructors"]
compatibility_date = "2021-09-29"
workers_dev = true
send_metrics = false
# pnpm wrangler:namespace
kv_namespaces = [
  { binding = "KV_STORE", id = "2db081aa524e4e91a81eeb9ac4a9088d" },
]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[env.production]
kv_namespaces = [
  { binding = "KV_STORE", id = "2db081aa524e4e91a81eeb9ac4a9088d" },
]

[env.production.triggers]
crons = [
  # https://crontab.guru/#*/2_*_*_*_*
  # Check monitors
  "*/2 * * * *",
  # https://crontab.guru/#*/10_*_*_*_*
  # Update remote csv monitors
  "*/10 * * * *",
]
